spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: jdbc:postgresql://localhost:5439/postgres
    username: namtrieu
    password: password
    hikari:
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS backend_service;
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: backend_service
    show-sql: true
    hibernate:
      ddl-auto: none


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: backend-service
    server: http://localhost:${server.port}
    title: Backend service
    version: 1.0.0